// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SysPatrimonio.Models;

#nullable disable

namespace SysPatrimonio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220526230710_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SysPatrimonio.Models.DbCategoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descricaocategoria")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Categoria", "public");
                });

            modelBuilder.Entity("SysPatrimonio.Models.DbDepartamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descricacaodepartamento")
                        .HasColumnType("text");

                    b.Property<int>("idlocal")
                        .HasColumnType("integer");

                    b.Property<string>("nomedepartamento")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Departamento", "public");
                });

            modelBuilder.Entity("SysPatrimonio.Models.DbFornecedor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("endereco")
                        .HasColumnType("text");

                    b.Property<string>("fone")
                        .HasColumnType("text");

                    b.Property<string>("nomefornecedor")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("fornecedor", "public");
                });

            modelBuilder.Entity("SysPatrimonio.Models.DbLocal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descicaolocal")
                        .HasColumnType("text");

                    b.Property<string>("nomelocal")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Local", "public");
                });

            modelBuilder.Entity("SysPatrimonio.Models.DbPatrimonio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dataaquisicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("databaixa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("descricaopatrimonio")
                        .HasColumnType("text");

                    b.Property<int>("idcategoria")
                        .HasColumnType("integer");

                    b.Property<int>("iddepartamento")
                        .HasColumnType("integer");

                    b.Property<int>("idlocal")
                        .HasColumnType("integer");

                    b.Property<string>("marcamodelo")
                        .HasColumnType("text");

                    b.Property<string>("nomepatrimonio")
                        .HasColumnType("text");

                    b.Property<string>("numeroetiqueta")
                        .HasColumnType("text");

                    b.Property<string>("valorpatrimonio")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Patrimonio", "public");
                });

            modelBuilder.Entity("SysPatrimonio.Models.DbUsuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("login")
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.Property<string>("senha")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Usuario", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
